export * from './IMovieRepository'
export * from './ITheaterRepository'
export * from './IScreenRepository'
export * from './IShowRepository'
export * from './IBookingRepository'
export * from './ISeatRepository'
